[tool.poetry]
name = "roam"
version = "0.2.1"
description = ""
authors = ["sapporojones <sapporojones@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
