name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.1.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python --version
        pip install --upgrade pip setuptools wheel tox sphinx
        pip install -U pytest
        pip install PEP517
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#    - name: Run tox doctests
#      run: |
#        tox -e doctests
    - name: Build docs and app with Tox and run pytest after building
      run: |
        tox
